# License record: IoT-devices, LLC : EO/zaD7NcdSfHLgB/OlzLx/6De/N5thMJ1PCZSsxhxqd3J4OoHK84QQgNlKVSh5X1lrEp0a0/8fRyTThM649FZNcQPydSrHadjHNH3pMPb6q4sDRHzsmt4vE18M3cfG+Rd7cMNqqlTl2IUu5J7mLiclji8di0FSBIB7UOnf14JxJ71oruGPkEiqK9yLAw4or

esphome:
  name: "esp32-ggreg20-v3"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-GGreg20-V3-ESP32"
    password: "vgcSNevqmK33"

captive_portal:

globals:
  - id: pulse_history
    type: int[60]
    restore_value: no
    initial_value: "{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}"

  - id: pulse_index
    type: int
    restore_value: no
    initial_value: "0"

  - id: pulse_sum
    type: int
    restore_value: no
    initial_value: "0"

# Here we calc and include to the firmware a power and dose values of ionizing radiation as sensor outputs
sensor:
- platform: pulse_counter
  id: geiger_cps
  internal: true
  pin:
    number: 23
    inverted: True
    mode:
      input: True
      # No pullup or pulldown on ESP32 side because of internal pullup set in hardware at GGreg20_V3 pulse output side
      pullup: False
      pulldown: False
  unit_of_measurement: 'CPS'
  name: 'Ionizing Radiation Power CPS'
  count_mode:
    rising_edge: DISABLE
    falling_edge: INCREMENT # GGreg20_V3 uses Active-Low logic
  # See ESPHome pulse_counter's internal filter in software mode issue here:
  # https://github.com/iotdevicesdev/GGreg20_V3-ESP32-HomeAssistant-ESPHome/issues/5
  # Issue walkaround is to disable these two lines:
  # use_pcnt: False ### disabled on 30/12/2024
  # internal_filter: 190us # for SBM20 tube, for J305 tube use 180us ### disabled on 30/12/2024
  accuracy_decimals: 0
  update_interval: 1s
  filters:
    delta: 1
  on_raw_value:
    then:
      - lambda: |-
          x=round(x/60); // esphome calculating based on pulses per minute. round required to avoid problem when esphome calc value less than 60 pulses per minute (for example 59.7)
          id(pulse_sum) -= id(pulse_history)[id(pulse_index)]; // remove old value from overall sum
          id(pulse_history)[id(pulse_index)] = x; // 'x' is the raw pulse count
          id(pulse_sum) += x; // add new value to overall sum

          id(pulse_index)++; // change array index where next value will be stores
          if (id(pulse_index) >= 60) id(pulse_index) = 0; // Reset at 60
  on_value:
    then:
      component.update: geiger_cpm

- platform: template
  id: geiger_cpm
  unit_of_measurement: 'CPM'
  name: 'Ionizing Radiation Power CPM'
  accuracy_decimals: 0
  update_interval: 1s
  state_class: measurement
  lambda: return id(pulse_sum);
  filters:
    delta: 1

- platform: copy
  source_id: geiger_cpm
  id: ionizing_radiaton_power
  unit_of_measurement: 'µSv/h'
  name: 'Ionizing Radiation Power'
  state_class: measurement
  icon: mdi:radioactive
  accuracy_decimals: 3
  filters:
    - skip_initial: 15
    - sliding_window_moving_average: # 15 measurements moving average (MA5) here
        window_size: 15
        send_every: 1
    - multiply: 0.0057 # 0.0057 original value or 0.00332 for J305 by IoT-devices tube conversion factor of pulses into uSv/Hour

- platform: integration
  name: "Total Ionizing Radiation Dose"
  unit_of_measurement: "uSv"
  sensor: ionizing_radiaton_power # link entity id to the pulse_counter values above
  icon: "mdi:radioactive"
  accuracy_decimals: 5
  time_unit: min # integrate values every next minute
  filters:
    # obtained dose. Converting from uSv/hour into uSv/minute: [uSv/h / 60] OR [uSv/h * 0.0166666667].
    # if my_dose_meter in CPM, then [0.0057 / 60 minutes] = 0.000095; so CPM * 0.000095 = dose every next minute, uSv.
    - multiply: 0.0166666667
